<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4018.2">
  <POU Name="FastTask_Main" Id="{84d8777c-4062-4308-b50a-cec8cd308644}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM FastTask_Main
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
CO_BdlCount_Auto();

CO_StkRel_Cyl_FastOutput();

]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>